object DependenciesVersions {
    const val jvm = "11"
    const val kotlin = "1.6.0"
    const val gradle = "7.0.3"
    const val ktx = "1.6.0"
    const val coroutines = "1.5.0"
    const val appcompat = "1.3.1"
    const val constraint = "2.1.1"
    const val material = "1.4.0"
    const val lifecycle = "2.4.0"
    const val navigation = "2.3.5"
    const val koin = "3.1.3"
    const val ktor = "1.6.3"
    const val glide = "4.12.0"
    const val slf4j = "1.7.26"
    const val androidArch = "2.1.0"
    const val paging = "3.1.1"
}